import React from "react"
import Layout from "../components/layout"
import SideMenu from "../components/menu"

//should make this a topic page template at some point and have the total amount autogenerated
// based off folders perhaps present under content

export default function TopicPage({ data, location }) {
  return (
    <div>
      <SideMenu location={location} />
      <Layout>
        <div>
          <div>
            <h1>Hello</h1>
          </div>
        </div>
      </Layout>
    </div>
  )
}
